apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fairline
data:
  DB_URL: "jdbc:postgresql://fairline-dev-postgres.c90c2ii6yx10.ap-northeast-2.rds.amazonaws.com:5432/concert"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  USER_AUTH_SERVICE_BASE_URL: "http://user-auth-service:8080"
  EMAIL_FROM_ADDRESS: "no-reply@example.com"
  EMAIL_FROM_NAME: "Fairline Ticket Team"
  TOSS_API_BASE: "https://api.tosspayments.com"
  TOSS_CONFIRM_URL: "https://api.tosspayments.com/v1/payments/confirm"
