apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fairline-ingress
  namespace: fairline
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - skala3-cloud1-team4.cloud.skala-ai.com
      secretName: fairline-tls
  rules:
    - host: skala3-cloud1-team4.cloud.skala-ai.com
      http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: user-auth-service
                port:
                  number: 8080
          - path: /api/concerts
            pathType: Prefix
            backend:
              service:
                name: concert-service
                port:
                  number: 8080
          - path: /api/ticketing
            pathType: Prefix
            backend:
              service:
                name: queue-service
                port:
                  number: 8080
          - path: /api/seats
            pathType: Prefix
            backend:
              service:
                name: ticketing-service
                port:
                  number: 8080
          - path: /api/bookings
            pathType: Prefix
            backend:
              service:
                name: ticketing-service
                port:
                  number: 8080
          - path: /api/payments
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 8080
          - path: /ops/incidents
            pathType: Prefix
            backend:
              service:
                name: incident-api
                port:
                  number: 18088
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 5173
