apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: fairline
type: Opaque
stringData:
  DB_USER: "skala"
  DB_PASSWORD: "skala1229"
  JWT_SECRET: "your-secret-key-min-32-characters-long-for-hs256-algorithm-security"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  TOSS_SECRET_KEY: ""
