BEGIN;

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS concert;
CREATE SCHEMA IF NOT EXISTS ticketing;
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS queue;

CREATE TABLE IF NOT EXISTS auth.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    phone VARCHAR(50),
    fan_score INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS concert.artist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS concert.concerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT REFERENCES concert.artist(id),
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT,
    location VARCHAR(255),
    duration_minutes INTEGER,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_concerts_artist_id
    ON concert.concerts (artist_id);

CREATE INDEX IF NOT EXISTS idx_concerts_visible
    ON concert.concerts (is_visible);

CREATE TABLE IF NOT EXISTS concert.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id BIGINT NOT NULL REFERENCES concert.concerts(id) ON DELETE CASCADE,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    total_seats INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_schedules_concert_id
    ON concert.schedules (concert_id);

CREATE INDEX IF NOT EXISTS idx_schedules_start_time
    ON concert.schedules (start_time);

CREATE TABLE IF NOT EXISTS concert.seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section VARCHAR(50) NOT NULL,
    row_number INTEGER NOT NULL,
    seat_number INTEGER NOT NULL,
    schedule_id BIGINT NOT NULL REFERENCES concert.schedules(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    held_by BIGINT,
    held_until TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    grade VARCHAR(50),
    price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT chk_concert_seats_status
        CHECK (status IN ('AVAILABLE', 'HOLD', 'RESERVED')),
    CONSTRAINT uq_concert_seats_schedule_position
        UNIQUE (schedule_id, section, row_number, seat_number)
);

CREATE INDEX IF NOT EXISTS idx_seats_schedule_id
    ON concert.seats (schedule_id);

CREATE INDEX IF NOT EXISTS idx_seats_schedule_status
    ON concert.seats (schedule_id, status);

CREATE TABLE IF NOT EXISTS ticketing.bookings (
    id UUID PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth.users(id),
    schedule_id BIGINT NOT NULL REFERENCES concert.schedules(id),
    total_price NUMERIC(12, 2),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    canceled_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_bookings_user_id
    ON ticketing.bookings (user_id);

CREATE INDEX IF NOT EXISTS idx_bookings_schedule_id
    ON ticketing.bookings (schedule_id);

CREATE INDEX IF NOT EXISTS idx_bookings_status
    ON ticketing.bookings (status);

CREATE INDEX IF NOT EXISTS idx_bookings_expires_at
    ON ticketing.bookings (expires_at);

CREATE TABLE IF NOT EXISTS ticketing.booking_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id UUID NOT NULL REFERENCES ticketing.bookings(id) ON DELETE CASCADE,
    seat_id BIGINT NOT NULL REFERENCES concert.seats(id),
    CONSTRAINT uq_booking_items_booking_seat
        UNIQUE (booking_id, seat_id)
);

CREATE INDEX IF NOT EXISTS idx_booking_items_booking_id
    ON ticketing.booking_items (booking_id);

CREATE INDEX IF NOT EXISTS idx_booking_items_seat_id
    ON ticketing.booking_items (seat_id);

CREATE TABLE IF NOT EXISTS payment.payments (
    id UUID PRIMARY KEY,
    amount NUMERIC(12, 2),
    status VARCHAR(30),
    created_at TIMESTAMP WITH TIME ZONE,
    expired_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    idempotency_key VARCHAR(255),
    booking_id UUID NOT NULL REFERENCES ticketing.bookings(id),
    order_name VARCHAR(255),
    pg_provider VARCHAR(100),
    pg_order_id VARCHAR(255),
    pg_payment_key VARCHAR(255),
    pg_status VARCHAR(100),
    submitted_at TIMESTAMP WITH TIME ZONE,
    hard_deadline_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_payments_booking_id UNIQUE (booking_id),
    CONSTRAINT uq_payments_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_payments_pg_order_id UNIQUE (pg_order_id),
    CONSTRAINT uq_payments_pg_payment_key UNIQUE (pg_payment_key)
);

CREATE INDEX IF NOT EXISTS idx_payments_status
    ON payment.payments (status);

CREATE INDEX IF NOT EXISTS idx_payments_updated_at
    ON payment.payments (updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_payments_expired_at
    ON payment.payments (expired_at);

CREATE INDEX IF NOT EXISTS idx_payments_hard_deadline_at
    ON payment.payments (hard_deadline_at);

CREATE TABLE IF NOT EXISTS payment.refunds (
    id UUID PRIMARY KEY,
    payment_id UUID NOT NULL REFERENCES payment.payments(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    reason_code VARCHAR(50) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    pg_refund_id VARCHAR(100),
    requested_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_refunds_payment_id
    ON payment.refunds (payment_id);

CREATE TABLE IF NOT EXISTS payment.payment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id UUID NOT NULL REFERENCES payment.payments(id) ON DELETE CASCADE,
    event_type VARCHAR(40) NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20),
    idempotency_key VARCHAR(255),
    pg_event_id VARCHAR(100),
    payload_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_payment_events_payment_id
    ON payment.payment_events (payment_id);

CREATE INDEX IF NOT EXISTS idx_payment_events_event_type
    ON payment.payment_events (event_type);

CREATE TABLE IF NOT EXISTS queue.user_artist_fan_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth.users(id),
    artist_id BIGINT NOT NULL REFERENCES concert.artist(id),
    booking_score INTEGER NOT NULL DEFAULT 0,
    external_score INTEGER NOT NULL DEFAULT 0,
    total_score INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_artist_fan_scores_user_artist
        UNIQUE (user_id, artist_id)
);

CREATE INDEX IF NOT EXISTS idx_user_artist_fan_scores_user_id
    ON queue.user_artist_fan_scores (user_id);

CREATE INDEX IF NOT EXISTS idx_user_artist_fan_scores_artist_id
    ON queue.user_artist_fan_scores (artist_id);

COMMIT;
