-- CDC Migration: align payment.payment_events and add outbox/inbox tables
-- Run ONCE on RDS before deploying Debezium.
-- Safe to re-run (all statements are idempotent).

BEGIN;

-- payment.payment_events: add columns required by Debezium Outbox Event Router
-- (Hibernate ddl-auto=update adds these on service startup, but explicit migration is safer)
ALTER TABLE payment.payment_events
    ADD COLUMN IF NOT EXISTS event_id        UUID,
    ADD COLUMN IF NOT EXISTS event_version   VARCHAR(20)  DEFAULT 'v1',
    ADD COLUMN IF NOT EXISTS producer        VARCHAR(60)  DEFAULT 'payment-service',
    ADD COLUMN IF NOT EXISTS aggregate_type  VARCHAR(40)  DEFAULT 'payment',
    ADD COLUMN IF NOT EXISTS aggregate_id    VARCHAR(100),
    ADD COLUMN IF NOT EXISTS ordering_key    VARCHAR(100),
    ADD COLUMN IF NOT EXISTS correlation_id  VARCHAR(100),
    ADD COLUMN IF NOT EXISTS causation_id    VARCHAR(100),
    ADD COLUMN IF NOT EXISTS trace_id        VARCHAR(100),
    ADD COLUMN IF NOT EXISTS booking_id      UUID,
    ADD COLUMN IF NOT EXISTS publish_status  VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    ADD COLUMN IF NOT EXISTS published_at    TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS retry_count     INTEGER      NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_error      TEXT,
    ADD COLUMN IF NOT EXISTS occurred_at     TIMESTAMP WITH TIME ZONE;

-- Unique constraint on event_id (required for Debezium idempotency)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'uq_payment_events_event_id'
          AND conrelid = 'payment.payment_events'::regclass
    ) THEN
        ALTER TABLE payment.payment_events
            ADD CONSTRAINT uq_payment_events_event_id UNIQUE (event_id);
    END IF;
END $$;

-- ticketing.ticketing_outbox
CREATE TABLE IF NOT EXISTS ticketing.ticketing_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        UUID          NOT NULL UNIQUE,
    event_type      VARCHAR(80)   NOT NULL,
    event_version   VARCHAR(20)   NOT NULL DEFAULT 'v1',
    producer        VARCHAR(60)   NOT NULL DEFAULT 'ticketing-service',
    aggregate_type  VARCHAR(40)   NOT NULL,
    aggregate_id    VARCHAR(100),
    ordering_key    VARCHAR(100),
    booking_id      UUID,
    payment_id      UUID,
    correlation_id  VARCHAR(100),
    payload_json    JSONB,
    occurred_at     TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE,
    publish_status  VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    published_at    TIMESTAMP WITH TIME ZONE,
    retry_count     INTEGER       NOT NULL DEFAULT 0,
    last_error      TEXT
);

CREATE INDEX IF NOT EXISTS idx_ticketing_outbox_publish_status
    ON ticketing.ticketing_outbox (publish_status, created_at);

-- ticketing.ticketing_inbox_events
CREATE TABLE IF NOT EXISTS ticketing.ticketing_inbox_events (
    id              UUID PRIMARY KEY,
    dedupe_key      VARCHAR(255)  NOT NULL UNIQUE,
    event_type      VARCHAR(80)   NOT NULL,
    producer        VARCHAR(60)   NOT NULL,
    booking_id      UUID,
    payment_id      UUID,
    aggregate_id    VARCHAR(120),
    pg_order_id     VARCHAR(120),
    pg_payment_key  VARCHAR(120),
    status          VARCHAR(40)   NOT NULL,
    duplicate_count INTEGER,
    received_at     TIMESTAMP WITH TIME ZONE,
    last_seen_at    TIMESTAMP WITH TIME ZONE
);

-- ticketing.reconciliation_tasks
CREATE TABLE IF NOT EXISTS ticketing.reconciliation_tasks (
    id                  UUID PRIMARY KEY,
    booking_id          UUID         NOT NULL REFERENCES ticketing.bookings(id) ON DELETE CASCADE,
    payment_id          UUID,
    mismatch_type       VARCHAR(80)  NOT NULL,
    status              VARCHAR(40)  NOT NULL,
    booking_status      VARCHAR(40),
    reason_code         VARCHAR(120),
    user_id             BIGINT,
    concert_id          BIGINT,
    schedule_id         BIGINT,
    seat_ids_csv        VARCHAR(1000),
    pg_order_id         VARCHAR(120),
    pg_payment_key      VARCHAR(120),
    amount              BIGINT,
    requested_at        TIMESTAMP WITH TIME ZONE,
    last_processed_at   TIMESTAMP WITH TIME ZONE,
    next_retry_at       TIMESTAMP WITH TIME ZONE,
    completed_at        TIMESTAMP WITH TIME ZONE,
    retry_count         INTEGER,
    last_error          VARCHAR(1000)
);

COMMIT;
