apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-service
  namespace: fairline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-service
  template:
    metadata:
      labels:
        app: ticketing-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: NotIn
                    values:
                      - g5.xlarge
      containers:
        - name: ticketing-service
          image: 881490135253.dkr.ecr.ap-northeast-2.amazonaws.com/team4-ticketing-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://fairline-dev-postgres.c90c2ii6yx10.ap-northeast-2.rds.amazonaws.com:5432/concert?currentSchema=ticketing,concert,public"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "3"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "1"
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_READINESSSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: "ticketing-service"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 10
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
