apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: fairline
  labels:
    monitoring: enabled
spec:
  selector:
    app: queue-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
